FROM ubuntu:24.04 AS dap-rt-reporter-prerelease-image 

RUN echo "Prerelease build target selected. Installing DAP RT-Reporter from repository."

# Avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Base image installation
RUN apt update && apt install -y --no-install-recommends \
    python3 \
    python-is-python3 \
    git \
    gdb \
    lldb \
    && rm -rf /var/lib/apt/lists/*

# Install poetry using pip (available to all users)
RUN apt update && apt install -y pipx && \
    pipx ensurepath && \
    pipx install poetry
# Add pipx to PATH for all users
ENV PATH="/root/.local/bin:${PATH}"
    
# Working directory setup
WORKDIR /workspaces

# Restore interactive prompts during package installation
ENV DEBIAN_FRONTEND=

RUN git clone -b develop https://github.com/invap/dap-rt-reporter.git /workspaces/dap-rt-reporter
