[project]
name = "dap-rt-reporter"
version = "0.1.0"
description = "Library to configure, execute and report execution trace using DAP"
authors = [
  {name = "Alí Veizaga", email = "abveizaga@invap.com.ar"},
  {name = "Juan Ignacio Vaccarezza", email =  "jivaccarezza@invap.com.ar"},
]
license = "SPDX-License-Identifier: AGPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.10,<4.0"
packages = [
    { include = "dap_rt_reporter"},
]
dependencies = [
  "dap-python (>=0.5.0)",
  "toml (>=0.10.2,<0.11.0)"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
