from rt_rabbitmq_wrapper.rabbitmq_utility import RabbitMQ_server_config, RabbitMQ_exchange_config

rabbitmq_server_config = RabbitMQ_server_config()
rabbitmq_event_exchange_config = RabbitMQ_exchange_config()